name: CD

on:
  push:
    branches: [main]

env:
  NODE_VERSION: 16.x

jobs:
  bump-version:
    name: Bump package.json Version
    if: ${{ !startsWith(github.event.head_commit.message, '[CI/CD]') }}
    runs-on: ubuntu-latest
    outputs:
      tag-name: ${{ steps.bump.outputs.newTag }}

    steps:
      - uses: actions/checkout@v2
        with:
          # This is a public_repo Github personal access token.
          token: ${{ secrets.WORKFLOW_GITHUB_TOKEN }}

      - name: Bump version
        id: bump
        uses: phips28/gh-action-bump-version@v9.0.1
        with:
          tag-prefix: 'v'
          commit-message: '[CI/CD]: bump to {{version}}'

  github-release:
    name: Release on Github
    needs: bump-version
    if: startsWith(needs.bump-version.outputs.tag-name, 'v')
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ needs.bump-version.outputs.tag-name }}

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ needs.bump-version.outputs.tag-name }}

  npm-release:
    name: Release on NPM
    needs: bump-version
    if: startsWith(needs.bump-version.outputs.tag-name, 'v')
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ needs.bump-version.outputs.tag-name }}

      - name: Use node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install
        run: npm ci

      - name: Build
        run: npm run prepack

      - name: Release
        uses: JS-DevTools/npm-publish@v1
        with:
          # This is an automation type NPM access token.
          token: ${{ secrets.WORKFLOW_NPM_TOKEN }}
